apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
spec:
  template:
    spec:
      containers:
      - name: mysqldb
        env:
        - name: MYSQL_DATABASE
          value: ecomerce_sta
