apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: mysqldb
    environment: prod
spec:
  ports:
    - port: 3309
      targetPort: 3306
      protocol: TCP
      name: mysql

