apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

replicas:
  - name: backend
    count: 3
  - name: mysqldb
    count: 1

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml