apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: angular-dev-app
  namespace: argocd
spec:
  project: angular-dev-project
  source:
    repoURL: https://github.com/stevymonkam/kubernetes-argocd-angular-javasprintboot.git
    targetRevision: feature
    path: apps/frontend/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true