apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: angular-staging-app
  namespace: argocd
spec:
  project: staging-project
  source:
    repoURL: https://github.com/stevymonkam/kubernetes-argocd-angular-javasprintboot.git
    targetRevision: main
    path: apps/frontend/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true