apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
- ../../base
patchesStrategicMerge:
 - deployment-patch.yaml
  - service-patch.yaml
replicas:
  - name: backend
    count: 3
  - name: mysqldb
    count: 1