apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: stevymonkam/imageback2:latest
        ports:
        - containerPort: 8086
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysqldb:3306/ecomerce_prod?useSSL=false"
        - name: SPRING_DATASOURCE_USERNAME
          value: "stevy"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "manounou"



            
