apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: backend
  labels:
    app: backend
spec:
  type: NodePort  # ← Changez seulement ça
  ports:
    - port: 8086
      targetPort: 8086
      nodePort: 30086  # ← Ajoutez cette ligne
  selector:
    app: backend