apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
  - ../../base
patchesStrategicMerge:
  - service-patch.yaml
  - deployment-patch.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: mysqldb
