apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - path: service-patch.yaml
    target:
      kind: Service
      name: mysqldb
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: mysqldb
