apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: mysqldb
    environment: prod
spec:
  ports:
    - port: 3308
      targetPort: 3306
      protocol: TCP
      name: mysqldb
  selector:
    app: mysqldb
  type: ClusterIP        # Ajouter cette ligne pour surcharger clusterIP: None
  clusterIP: ""          # Ou explicitement définir clusterIP à vide pour un service standard




