apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: mysqldb
    environment: prod
spec:
  ports:
    - port: 3308
      targetPort: 3306
      protocol: TCP
      name: mysqldb
  selector:
    app: mysqldb
  # Supprimer complètement clusterIP: None en le redéfinissant
  $patch: replace





