apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    environment: prod
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysqldb
 











