apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
  namespace: dev
spec:
  selector:
    app: angular-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
<<<<<<< HEAD
      nodePort: 30089
=======
      nodePort: 30083

>>>>>>> feature
