apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: mysql-config
    literals:
      - MYSQL_DATABASE=ecomerce