apiVersion: v1
kind: Service
metadata:
  name: mysqldb
  labels:
    app: mysqldb
    environment: dev
spec:
  ports:
    - port: 3307
      targetPort: 3306
      protocol: TCP
      name: mysqldb


