apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev 
resources:
- ../../base
patchesStrategicMerge:
- service-patch.yaml


#nb : pour que l'asyc sur arco fonctione il faut changer le nom
# de l'image que la pipeline a ecrit par le nom de l'image qui est 
# dans base voir exemple dans overlays/dev/kustomization.yaml
# donc remplacer angular-app-dev par stevymonkam/front5