apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev 
resources:
- ../../base
patchesStrategicMerge:
- service-patch.yaml

# Surcharge de l'image
images:
- name: stevymonkam/front5 # remplacez par le nom dans votre deployment base
  newName: stevymonkam/frontdevs3new
  newTag: latest
